### ISSUE TITLE
Issue with bulk host operation

### ISSUE THREAD

**Issue by oxsannikova** [macvjuhu/fmc_rest_client#16]
While trying to work with the new bulk post functionality in release 6.2.3.3, have receved the following error:

REST called failed: ('generic', 'The value is mandatory as override is not enabled .')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fmc_rest_client/core/base_clients.py", line 322, in create
    response_resources = self._bulk_create(resource, bulk_limit)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fmc_rest_client/core/base_clients.py", line 306, in _bulk_create
    json_resp = self.post(url_path, post_data)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fmc_rest_client/core/base_clients.py", line 280, in post
    return self.rest_call('post', url_path, data)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fmc_rest_client/core/base_clients.py", line 160, in rest_call
    raise e
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fmc_rest_client/core/base_clients.py", line 157, in rest_call
    raise e
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fmc_rest_client/core/base_clients.py", line 137, in rest_call
    status_code, response_json =  self._rest_call(method, url, post_data, headers, offset, expanded)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fmc_rest_client/core/base_clients.py", line 197, in _rest_call
    raise ResourceException(ResourceException.GENERIC, desc)
fmc_rest_client.core.base_clients.ResourceException: ('generic', 'The value is mandatory as override is not enabled .')

The script it very simple:

class Host(ObjectResource):
    bulk_operations = ['POST']

fmc.create(fmc_hosts) #where fmc_hosts is a list of Host objects, created with the Host(name, value) function.

**Comment by oxsannikova** [comment]
Found an error in the script: I have to redeclair the whole class in my script:
class Host(ObjectResource):
    bulk_operations = ['POST']
    def __init__(self, name=None, value=None):
        super().__init__(name)
        self.value = value

Can you add POST operations for the following objects into the objects.py?

Host Objects, Network Objects, Range Objects, 
 Network Groups, Protocol Port Objects, ICMPv4 Port objects, ICMPv6 Port Objects,
Port Object Groups, Url Objects, Url Groups, Vlan Tag Objects, Vlan Tag Groups, and SLA Monitor Objects
